### ISSUE TITLE
Provided attributes like dialog-dismiss do not work for paper-icon-button elements

### ISSUE THREAD

**Issue by fakiolinho** [PolymerElements/paper-dialog-behavior#69] opened 2016-02-07 15:29 UTC
Attributes `dialog-dismiss` and `dialog-confirm` work only for `paper-button` and not for `paper-icon-button`. Following fails to close our modal:
```html
<paper-dialog id="dialog">
    <h2>Title</h2>
    <paper-icon-button icon="clear" dialog-dismiss></paper-icon-button>
    ...
</paper-dialog>
```
This is very important for cases we need a closing `x` icon button to dismiss the modal (a common option we need which is not offered by Polymer) and we still need the closing reason in our app. If we use a `paper-icon-button` to do this job, then provided attributes do not work so we have to use a custom event handler to close the modal and then gain access to the `closingReason` which is somewhat cumbersome:

```html
<paper-dialog id="dialog">
    <h2>Title</h2>
    <paper-icon-button icon="clear" on-tap="_closeModal"></paper-icon-button>
    ...
</paper-dialog>
```

```javascript
...
_closeModal: function(e) {
    this.$.dialog.close();
    var reason = this.$.dialog.closingReason;
    ...
}
```

Maybe the best solution for all those will be to add the closing `x` icon button option for `paper-dialog` element where provided attributes like `data-dismiss` are going to work as wanted. Above is tested with Polymer 1.2.4.

**Comment by valdrinkoshi** [comment] 2016-02-09 00:01
Closing as duplicate of https://github.com/PolymerElements/paper-dialog-behavior/issues/66.
It's being fixed in https://github.com/PolymerElements/paper-dialog-behavior/pull/67

**Closed by valdrinkoshi** 2016-02-09 00:01 UTC
