### ISSUE TITLE
Nesting paper-toolbar in paper-dialog causes alignment issues

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-dialog-behavior#35] opened 2015-10-22 16:38 UTC
From https://github.com/PolymerElements/paper-toolbar/issues/38
__paper-dialog-behavior__ is adding margin: https://github.com/PolymerElements/paper-dialog-behavior/blob/master/paper-dialog-common.css#L13  should it do it?

**Comment by valdrinkoshi** [comment] 2016-02-26 21:56
Setting the `margin` on the `:host` is a quicker way to ensure that gap from the viewport.
Probably this could be done as well by setting `max-width: calc(100vw - 48px);`... I'll experiment with this.

**Comment by valdrinkoshi** [comment] 2016-02-26 22:34
Ok, so the problem is not really caused by setting `margin: 24px 40px`, but by
```css
      :host > ::content > * {
        margin-top: 20px;
        padding: 0 24px;  /* this one causes the padding left/right */
      }

      :host > ::content > .no-padding {
        padding: 0;
      }

      :host > ::content > *:first-child {
        margin-top: 24px; /* this one causes the margin top */
      }
```

This is done to give enough vertical & horizontal room to each child of the `paper-dialog`. 
I'm not sure why we've chosen to set `padding` instead of `margin` for the horizontal space though.

At this point, changing these styles would be a breaking change, so I'd recommend we suggest to Polymer users to set the proper styles:
```html
<style is="custom-style">
  paper-dialog > paper-toolbar {
    margin: 0;
    padding: 0;
  };
</style>

<paper-dialog>
  <paper-toolbar>
    <paper-button>menu</paper-button>
    <h2 class="title">Title</h2>
  </paper-toolbar>
</paper-dialog>

**Comment by valdrinkoshi** [comment] 2016-02-26 22:42
@notwaldorf @blasten we currently handle the css class `buttons` for the bottom toolbar, so it would be fair to also have a css class `header`, right?

**Comment by valdrinkoshi** [comment] 2016-03-02 00:39
Ideally, the styles shouldn't be applied to content (since content could be anything). We should instead have a `content` or `body` class that explicitly styles those elements. Otherwise, we should expect the Polymer user to style those. This wouldn't even require a `header` class (since the margin would not be applied to an element that doesn't have `content` class)

**Comment by valdrinkoshi** [comment] 2016-04-01 22:51
Closing this as not actionable

**Closed by valdrinkoshi** 2016-04-01 22:51 UTC
Labels: breaking-change, p1 - backlog, question
